Added null safety
shagun25/SheHeroes pull request #65
Opened 2021-03-26 09:59 UTC by Samdid

## Related Issue 

- Null Safety - I have to migrate the current non-nullable project to the nullable project  

Closes: #37 

### Describe the changes you've made

I have migrated the non-nullable project to nullable project by upgrading the SDK version and some packages. Some packages were non-compatible to null safety, then I have upgraded them by downloading the latest version of that package which is compatible to null safety. Also, changed some code manually to make the project nullable.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
None

2021-03-26 10:00 UTC, Samdid commented
@shagun25 I have migrated the complete project, please review and merge this PR.

2021-03-26 15:40 UTC, hiashutoshsingh requested changes
Hey, @Samdid thanks for submitting PR.
This PR needs a lot of changes.
1) I can see a change on 2 files only, the rest files should adhere to null safety.
2) can't see the pubspec.yaml changes for packages.
3) unnecessary cli folder is added by mistake


Please resolve these changes, I am sure you will able to pull this off. 
Let me know if you face any blocker.

2021-03-26 15:40 UTC, hiashutoshsingh commented on Sheheroes_WatchOS/pubspec.lock
> +# See https://dart.dev/tools/pub/glossary#lockfile
Please remove this lock file from commit, but keep this in your local.
See Why: https://dart.dev/guides/libraries/private-files#pubspeclock

2021-03-26 15:40 UTC, hiashutoshsingh commented on my_cli/.gitignore
> +# Files and directories created by pub
Please remove cli folder, there is no need for this I guess.

2021-03-26 15:40 UTC, hiashutoshsingh commented on my_cli/CHANGELOG.md
> +
Please remove cli folder.

2021-03-26 15:40 UTC, hiashutoshsingh commented on my_cli/README.md
> +in `lib/`, and example unit test in `test/`.
Please remove cli folder.

2021-03-26 15:40 UTC, hiashutoshsingh commented on my_cli/analysis_options.yaml
> +# see https://github.com/dart-lang/pedantic#enabled-lints.
Please remove cli folder.

2021-03-26 15:40 UTC, hiashutoshsingh commented on my_cli/bin/my_cli.dart
> +
Please remove cli folder.

2021-03-26 15:40 UTC, hiashutoshsingh commented on my_cli/lib/my_cli.dart
> +int calculate() {
Please remove cli folder.

2021-03-26 15:40 UTC, hiashutoshsingh commented on my_cli/pubspec.yaml
> +# version: 1.0.0
Please remove cli folder.

2021-03-26 15:40 UTC, hiashutoshsingh commented on my_cli/pubspec.lock
> +# Generated by pub
Please remove cli folder.

2021-03-26 15:40 UTC, hiashutoshsingh commented on my_cli/test/my_cli_test.dart
> +
Please remove cli folder.

2021-03-26 15:40 UTC, hiashutoshsingh commented on pubspec.lock
> +# See https://dart.dev/tools/pub/glossary#lockfile
Please remove this lock file from commit, but keep this in your local.
See Why: https://dart.dev/guides/libraries/private-files#pubspeclock

2021-03-26 16:25 UTC, Samdid commented
@hiashutoshsingh I will resolve all the changes asap

2021-04-05 16:07 UTC, hiashutoshsingh commented
Hey @Samdid what's the update on the above ones, this is pending for a long time. Let's try to resolve all commented issues in 2-3 days, I am sure you will be able to pull this off.

2021-04-05 18:00 UTC, Samdid commented
> Hey @Samdid what's the update on the above ones, this is pending for a long time. Let's try to resolve all commented issues in 2-3 days, I am sure you will be able to pull this off.

Okay

2021-04-14 03:47 UTC, hiashutoshsingh commented
> > Hey @Samdid what's the update on the above ones, this is pending for a long time. Let's try to resolve all commented issues in 2-3 days, I am sure you will be able to pull this off.
> 
> Okay

Hey @Samdid what is the status of the above?

2021-04-22 07:48 UTC, hiashutoshsingh commented
> Hey @Samdid what's the update on the above ones, this is pending for a long time. Let's try to resolve all commented issues in 2-3 days, I am sure you will be able to pull this off.

any updates on the above will be closing this PR, wanted to give chance to others.

2021-04-23 12:13 UTC, closed without merging