Fake Call Functionality Added Integrate With Emergency Dashboard
shagun25/SheHeroes pull request #69
Opened 2021-03-27 12:56 UTC by SamarpanCoder2002

Issue: #49 

- Add Fake Call Functionality, 
1. User Can Give Fake caller name. 
2. Time Duration after the fake calling Screen Show
3. Ringtone will be default ringtone of phone

Closes: #49

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
Video demo link: https://drive.google.com/file/d/1U96XNZgFqkPU1Y57AeABytpl5kp56rgQ/view?usp=sharing

Try this app connecting with the physical device as developer mode, for better sound experience.....

Hope you review it and merge it soon @shagun25 @hiashutoshsingh ...That a nice project to work with... Thank u

2021-03-27 16:20 UTC, hiashutoshsingh requested changes
PR looks good. Just small changes needed.

Have a look and let me know if you are facing any blocker.

2021-03-27 16:20 UTC, hiashutoshsingh commented on lib/pages/emergency_dashboard.dart
>                // mainAxisAlignment = MainAxisAlignment.spaceEvenly
add shrinkwrap as true here is listview so that the ListView only occupies the space it needs

2021-03-27 16:20 UTC, hiashutoshsingh commented on lib/pages/fake_call_support.dart
> +    super.dispose();
implement all dispose functionalities before super.dispose(), there should be no code written below super.dispose

2021-03-27 16:20 UTC, hiashutoshsingh commented on lib/pages/fake_call_support.dart
> +              children: <Widget>[
add shrinkWrap:true

2021-03-27 16:20 UTC, hiashutoshsingh commented on lib/pages/fake_incoming_call_screen.dart
> +    FlutterRingtonePlayer.stop();
move this dispose function before super.dispose

2021-03-27 16:20 UTC, hiashutoshsingh commented on lib/pages/switcher.dart
> +            //mainAxisAlignment: MainAxisAlignment.spaceEvenly,
use shrikWrap:true

2021-03-27 16:20 UTC, hiashutoshsingh commented on lib/ui/homescreen.dart
>              // mainAxisAlignment = MainAxisAlignment.spaceEvenly
use shrikWrap:true

2021-03-27 16:22 UTC, SamarpanCoder2002 commented
I willl made changes very soon...Thanks for review

2021-03-27 16:29 UTC, SamarpanCoder2002 commented
Hello @shagun25 @hiashutoshsingh .. I made changes according to the instruction...please take a look here... and if all ok, then merge it...Thank u

2021-03-27 18:49 UTC, SamarpanCoder2002 commented
Hope you merge it soon @shagun25 @hiashutoshsingh

2021-03-28 06:19 UTC, SamarpanCoder2002 commented
Hello @hiashutoshsingh .... if I make `shrinkwrap true` in listview, then unexpected look here:
<p>
<img src="https://user-images.githubusercontent.com/66327336/112744196-851f2800-8fbb-11eb-89db-e08be0e7388f.png" width="200">
<img src="https://user-images.githubusercontent.com/66327336/112744201-87818200-8fbb-11eb-9ee1-8662b0de1c22.png"  width="200">
</p>

2021-03-29 13:30 UTC, hiashutoshsingh commented
> Hello @hiashutoshsingh .... if I make `shrinkwrap true` in listview, then unexpected look here(For some of the pages,):
> 
> <img alt="" width="200" src="https://user-images.githubusercontent.com/66327336/112744196-851f2800-8fbb-11eb-89db-e08be0e7388f.png"> <img alt="" width="200" src="https://user-images.githubusercontent.com/66327336/112744201-87818200-8fbb-11eb-9ee1-8662b0de1c22.png">
> 
> So, I should keep it or not???????

Keep the code the same.
Change the parent container or the Scaffold background colour, it will work. @SamarpanCoder2002

2021-03-29 18:13 UTC, SamarpanCoder2002 commented
> > Hello @hiashutoshsingh .... if I make `shrinkwrap true` in listview, then unexpected look here(For some of the pages,):
> > So, I should keep it or not???????
> 
> Keep the code the same.
> Change the parent container or the Scaffold background colour, it will work. @SamarpanCoder2002

@hiashutoshsingh @shagun25 .... Problem Solved... Now you can review it and merge it

2021-03-29 18:16 UTC, SamarpanCoder2002 commented
@hiashutoshsingh @shagun25 ..... Now UI looks good...Please give a review and merge it .. thanks

2021-03-30 04:41 UTC, hiashutoshsingh approved these changes
Thanks for your contribution.

2021-03-30 04:41 UTC, merged

2021-03-30 04:44 UTC, SamarpanCoder2002 commented
> Thanks for your contribution.

Thanks for merge