Background Image Capture added as Immediate Capture with quick Actions
shagun25/SheHeroes pull request #73
Opened 2021-03-30 08:46 UTC by SamarpanCoder2002

## Related Issue 

- Info about the related issue 

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
Any additional information you want to give

2021-04-01 10:05 UTC, SamarpanCoder2002 commented
> Please take a look here @shagun25 @hiashutoshsingh
@shagun25 @hiashutoshsingh if there is no prb, please merge the pull request....For any problem, you can freely tell me... Actually, I can't make another pull request until it gets merged.... Thank u

2021-04-01 11:35 UTC, hiashutoshsingh requested changes
Please resolve the conflict also.

2021-04-01 11:43 UTC, SamarpanCoder2002 commented on lib/services/calls_and_messages_service.dart
> +    ImagePicker.pickImage(source: ImageSource.camera)
Open the camera to take image(Try in physical device as mentioned above)

2021-04-01 11:47 UTC, SamarpanCoder2002 commented on lib/main.dart
> +          localizedTitle: 'Immediate Capture',
As like Emergency call or message, Image Capture added with quick actions

2021-04-01 12:03 UTC, SamarpanCoder2002 commented on lib/main.dart
> +          localizedTitle: 'Immediate Capture',
Like that Immediate Capture as quick Actions
<img src="https://user-images.githubusercontent.com/66327336/113291150-37365700-9310-11eb-9e9c-1c5b30165187.jpg" width="200">

2021-04-01 12:05 UTC, SamarpanCoder2002 commented on lib/services/calls_and_messages_service.dart
> +    ImagePicker.pickImage(source: ImageSource.camera)
ImageSource.camera open the camera to take the image.....please try it as mentioned above.... I also attached a video link...Take a look here..... @shagun25 @hiashutoshsingh

2021-04-01 12:05 UTC, SamarpanCoder2002 commented
> Please resolve the conflict also.

@shagun25 @hiashutoshsingh ....Conflicts Solved and and all questions answered..... Hope you review it and merge it soon @hiashutoshsingh

2021-04-02 05:28 UTC, hiashutoshsingh commented on lib/services/calls_and_messages_service.dart
> +    ImagePicker.pickImage(source: ImageSource.camera)
Perfect!

2021-04-02 05:28 UTC, hiashutoshsingh approved these changes
Thanks for the contribution.

2021-04-02 05:29 UTC, merged