Fixed the overflowed signup screen
shagun25/SheHeroes pull request #76
Opened 2021-04-02 16:24 UTC by Samdid

## Related Issue 

-Sign up screen is overflowing so there is need to fix it  

Closes: #68 

### Describe the changes you've made

I have fixed the overflowing sign up screen by adding Singlechildscrollview widget and reducing the height of textfields

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
Any additional information you want to give
Screenshot:
![Screenshot_1617300018](https://user-images.githubusercontent.com/70087884/113434073-f583da00-93fd-11eb-838e-fcf609ca7338.png)

2021-04-03 17:38 UTC, hiashutoshsingh requested changes
Thanks for the PR. Just small changes(removing lock files) and then we are good to go.

2021-04-03 17:38 UTC, hiashutoshsingh commented on Sheheroes_WatchOS/pubspec.lock
> +# See https://dart.dev/tools/pub/glossary#lockfile
please remove this file

2021-04-03 17:38 UTC, hiashutoshsingh commented on pubspec.lock
> +# See https://dart.dev/tools/pub/glossary#lockfile
Please remove lock files from commit.

2021-04-03 18:25 UTC, Samdid commented on pubspec.lock
> +# See https://dart.dev/tools/pub/glossary#lockfile
Done

2021-04-03 18:25 UTC, Samdid commented on Sheheroes_WatchOS/pubspec.lock
> +# See https://dart.dev/tools/pub/glossary#lockfile
Done

2021-04-03 18:26 UTC, Samdid commented
@hiashutoshsingh Changes resolved

2021-04-04 17:24 UTC, hiashutoshsingh approved these changes
Thanks for the contribution.

2021-04-04 17:24 UTC, merged